name: curlgenerator
base: core24
version: git
summary: cURL Request Generator CLI tool
description: |
  cURL Request Generator is a CLI tool for generating cURL requests from OpenAPI specifications.
  It can generate both PowerShell and Bash scripts with cURL commands for testing REST APIs.
  
  The tool supports:
  - OpenAPI 2.0 and 3.0 specifications
  - JSON and YAML formats
  - Authorization headers
  - Azure Entra ID authentication
  - Custom base URLs and content types
  - Both PowerShell (.ps1) and Bash (.sh) script generation

grade: stable
confinement: strict

apps:
  curlgenerator:
    command: bin/curlgenerator
    plugs:
      - home
      - network

parts:
  curlgenerator:
    plugin: nil
    source: .
    build-snaps:
      - dotnet-sdk/8.0/stable
    stage-snaps:
      - dotnet-runtime-8.0
    build-packages:
      - ca-certificates
    override-build: |
      # Publish as framework-dependent to avoid glibc issues
      dotnet publish src/CurlGenerator/CurlGenerator.csproj \
        --configuration Release \
        --framework net8.0 \
        --output $CRAFT_PART_INSTALL/lib/curlgenerator
      
      # Create wrapper script
      mkdir -p $CRAFT_PART_INSTALL/bin
      cat > $CRAFT_PART_INSTALL/bin/curlgenerator << 'EOF'
      
      # Make the wrapper script executable
      chmod +x $CRAFT_PART_INSTALL/bin/curlgenerator