name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**/*"
      - "!.github/workflows/build.yml"
      - "!Cargo.toml"
      - "!Cargo.lock"
      - "!src/**/*.rs"
      - "!src/tests/resources/**/*"
    branches:
      - "*"
  pull_request:
    paths-ignore:
      - "**/*"
      - "!.github/workflows/build.yml"
      - "!Cargo.toml"
      - "!Cargo.lock"
      - "!src/**/*.rs"
      - "!src/tests/resources/**/*"
    branches:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: 👌 Verify build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 🛒 Checkout repository
        uses: actions/checkout@v6

      - name: 🦀 Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: 💾 Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: 🎨 Check formatting
        run: cargo fmt --all -- --check

      - name: 📎 Clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: 🛠️ Build
        run: cargo build --release --verbose

      - name: 🧪 Test
        run: cargo test --release --verbose
