name: Smoke Tests

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**/*"
      - "!.github/workflows/smoke-tests.yml"
      - "!Cargo.toml"
      - "!Cargo.lock"
      - "!src/**/*.rs"
      - "!test/**/*"
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  cli:
    name: 🧪 ${{ matrix.openapi }} (${{ matrix.version }}, ${{ matrix.format }}) ${{ matrix.shell }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: ["v2.0", "v3.0", "v3.1"]
        format: [json, yaml]
        shell: ["", "--bash"]
        openapi: ["petstore", "petstore-expanded"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 🛒 Checkout repository
        uses: actions/checkout@v6

      - name: 🦀 Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: 💾 Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: 🛠️ Build
        run: cargo build --release

      - name: 🚀 Generate scripts
        run: cargo run --release -- "test/OpenAPI/${{ matrix.version }}/${{ matrix.openapi }}.${{ matrix.format }}" --output ./out ${{ matrix.shell }} --skip-validation --no-logging
